FROM php:8.0.21RC1-fpm-alpine3.16
RUN apk --update --no-cache add git
RUN docker-php-ext-install pdo_mysql
RUN apk add --no-cache bash && \
    wget https://get.symfony.com/cli/installer -O - | bash -s - --install-dir /usr/local/bin && \
    mkdir /.symfony && \
    chown 1000:1000 /.symfony
COPY --from=composer /usr/bin/composer /usr/bin/composer
WORKDIR /var/www
CMD composer install ;  php-fpm
EXPOSE 9000